# Generated by Django 4.0.6 on 2023-03-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player', models.CharField(max_length=20)),
                ('Pts', models.FloatField()),
                ('TwoP', models.FloatField()),
                ('ThreeP', models.FloatField()),
                ('REB', models.FloatField()),
                ('AST', models.FloatField()),
                ('STL', models.FloatField()),
                ('BLK', models.FloatField()),
                ('Fouls', models.FloatField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
