# Generated by Django 4.0.6 on 2023-03-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('jersey', models.CharField(max_length=20)),
                ('team_name', models.CharField(max_length=20)),
                ('gp', models.FloatField()),
                ('seconds', models.FloatField()),
                ('two_m', models.FloatField()),
                ('two_a', models.FloatField()),
                ('two_pct', models.FloatField()),
                ('trey_m', models.FloatField()),
                ('trey_a', models.FloatField()),
                ('trey_pct', models.FloatField()),
                ('ft_m', models.FloatField()),
                ('ft_a', models.FloatField()),
                ('ft_pct', models.FloatField()),
                ('points', models.FloatField()),
                ('reb_o', models.FloatField()),
                ('reb_d', models.FloatField()),
                ('reb', models.FloatField()),
                ('ast', models.FloatField()),
                ('stl', models.FloatField()),
                ('blk', models.FloatField()),
                ('turnover', models.FloatField()),
                ('pfoul', models.FloatField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
