# Generated by Django 4.0.6 on 2023-03-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='seconds',
            field=models.CharField(max_length=20),
        ),
    ]
