# Generated by Django 4.0.6 on 2023-03-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0002_alter_player_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='league',
            field=models.CharField(default='plg', max_length=20),
            preserve_default=False,
        ),
    ]
