# Generated by Django 4.0.6 on 2023-03-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=20)),
                ('Ceo', models.CharField(max_length=20)),
                ('Gamer', models.CharField(max_length=20)),
                ('Score', models.IntegerField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=20)),
                ('Gamer', models.CharField(max_length=20)),
                ('Player', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=20)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
